services:

  mysql:
    image: mysql:8.0
    container_name: studentapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb_flyway
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: studentapp-backend:latest
    container_name: studentapp-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb_flyway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    image: studentapp-frontend:latest
    container_name: studentapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: